// Static site build for Netlify.
//
// This repo is frontend-only: the page is rendered once at build time with
// an absolute API URL baked into the form's action. The backend (submission,
// wallet challenge, and the asset catalog) is the Elixir/Phoenix service on
// the VPS, which lives on a different origin.
//
// Output layout matches the paths referenced in src/page.ts:
//
//   dist/index.html
//   dist/css/app.css
//   dist/js/app.js
//   dist/images/warthog-mark.svg
//   dist/images/favicon.svg
//   dist/images/favicon.png
//   dist/_redirects       (only when CATALOG_HOST is set)

import { mkdirSync, copyFileSync, writeFileSync, rmSync } from "node:fs";
import { renderHome } from "../src/page";

// Where the Phoenix backend lives. Override per-deploy with the
// API_BASE_URL build environment variable in Netlify.
// `??`, not `||`: an empty API_BASE_URL is a deliberate setting meaning
// "same origin" — the Netlify proxy fronts the backend, so the page emits
// relative URLs. `||` would treat "" as unset and fall back to the absolute
// :4445 URL, silently reintroducing the cross-origin request.
const API_BASE_URL =
  process.env.API_BASE_URL ?? "https://warthog-defitestnet.duckdns.org:4445";

// Origin the catalog is proxied from. Deliberately independent of
// API_BASE_URL: that one is now "" (same origin) on Netlify and carries
// :4445 everywhere else, and neither is a usable rewrite target — Netlify's
// proxy only speaks 80/443. This matches the origin netlify.toml's own
// redirects point at; nginx on the VPS routes these paths to Phoenix.
const CATALOG_BASE_URL =
  process.env.CATALOG_BASE_URL || "https://warthog-defitestnet.duckdns.org";

// Public catalog hostname, added to the Netlify site as a domain alias, where
// the asset hash sits at the root: testnet-assets.warthog.network/<hash>/logo.png.
// Unset and no _redirects file is written at all.
const CATALOG_HOST = process.env.CATALOG_HOST || "";

const OUT = "dist";

const apiUrl = `${API_BASE_URL.replace(/\/$/, "")}/api/submit`;

// In dev, esbuild and Tailwind write straight into dist/ and keep those
// files fresh, so copying the public/assets snapshots over them would
// serve stale output. HTML_ONLY re-renders just the page.
const htmlOnly = process.env.HTML_ONLY === "1";

mkdirSync(`${OUT}/css`, { recursive: true });
mkdirSync(`${OUT}/js`, { recursive: true });
mkdirSync(`${OUT}/images`, { recursive: true });

writeFileSync(`${OUT}/index.html`, renderHome(apiUrl));
copyFileSync("public/images/warthog-mark.svg", `${OUT}/images/warthog-mark.svg`);
copyFileSync("public/images/favicon.svg", `${OUT}/images/favicon.svg`);
copyFileSync("public/images/favicon.png", `${OUT}/images/favicon.png`);

// Unset: drop any file a previous build left behind, so turning CATALOG_HOST
// off actually takes effect instead of shipping a stale rule set.
if (!CATALOG_HOST) {
  rmSync(`${OUT}/_redirects`, { force: true });
}

// netlify.toml carries every catalog rule that applies sitewide, including
// the root-hash shape (/<hash>/logo.png). The one rule it cannot express is a
// hostname-scoped one, and exactly one is needed: on the catalog host a bare /
// should answer with the catalog rather than the submission form. Unscoping
// that would replace the form site's homepage with JSON.
if (CATALOG_HOST) {
  const catalogUrl = CATALOG_BASE_URL.replace(/\/$/, "");
  writeFileSync(
    `${OUT}/_redirects`,
    [
      "# Generated by scripts/build-static.ts — edit that, not this.",
      `# ${CATALOG_HOST} is a data host: its root is the catalog, not the form.`,
      "# Every other catalog rule lives in netlify.toml and applies sitewide.",
      `https://${CATALOG_HOST}/  ${catalogUrl}/assets.json  200!`,
      "",
    ].join("\n"),
  );
}

if (!htmlOnly) {
  copyFileSync("public/assets/app.css", `${OUT}/css/app.css`);
  copyFileSync("public/assets/app.js", `${OUT}/js/app.js`);
}

console.log(
  htmlOnly
    ? `index.html -> ${OUT}/  (API: ${apiUrl})`
    : `static site -> ${OUT}/  (API: ${apiUrl}${
        CATALOG_HOST ? `, catalog host: ${CATALOG_HOST}` : ""
      })`,
);
